syntax on
colorscheme jeff
set backspace=indent,eol,start
set expandtab
set softtabstop=2
set shiftwidth=2
set tabstop=2
set nobackup
set noswapfile
set number
set t_Co=16
set et
match ErrorMsg '\%100v.\+'
retab
